# try al the string functions

s = input("Enter a string: ")
print(s)
print("Length:\t",len(s))
print("Min: \t",min(s))
print("Max: \t",max(s))
print("Alphanumeric: \t",s.isalnum())
print("isAlpha: \t",s.isalpha())
print("isDigit: \t",s.isdigit())
print("isLower: \t",s.islower())
print("isUpper: \t",s.isupper())
print("Lowercase: \t",s.lower())
print("isupper: \t",s.upper())
print("isspace: \t",s.isspace())
print("isidentifier: \t",s.isidentifier())
print("endswith: \t",s.endswith("s"))
print("endswith: \t",s.endswith("s"))
print("startswith: \t",s.startswith('s'))
print("find: \t",s.find("s"))
print("count: \t",s.count("s"))
print("capitalize\t",s.capitalize())
print("title: \t",s.title())
print("swapcase: \t",s.swapcase())
print("replace: \t",s.replace('s','a'))
print("center: \t",s.center(10))
print("ljust: \t",s.ljust(5))
print("rjust: \t",s.rjust(5))
print("strip: \t",s.strip())
print("rstrip: \t",s.rstrip())
print("lstrip: \t",s.lstrip())